# Generated by Django 3.2.5 on 2021-08-14 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='room_price',
        ),
        migrations.AlterField(
            model_name='coefficient',
            name='end_date',
            field=models.DateField(default=datetime.date(2021, 8, 14)),
        ),
        migrations.AlterField(
            model_name='coefficient',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 8, 14)),
        ),
    ]
