# Generated by Django 3.2.5 on 2021-07-26 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Booking_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=200)),
                ('hotel_address', models.CharField(max_length=200)),
                ('hotel_email', models.CharField(max_length=200)),
                ('hotel_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_type_name', models.CharField(max_length=200)),
                ('hotel_tupe_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('room_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('smoking_yn', models.BooleanField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelcontent.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelcontent.room_types')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('until_date', models.DateField(blank=True, null=True)),
                ('agent_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelcontent.agent_reservation')),
                ('booking_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelcontent.booking_status')),
                ('hotels', models.ManyToManyField(to='hotelcontent.Hotel')),
            ],
        ),
    ]
