# Generated by Django 3.2.5 on 2021-07-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_description',
            field=models.TextField(default='Описание отеля'),
        ),
    ]
