# Generated by Django 3.2.5 on 2021-08-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0002_auto_20210813_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsimages',
            name='photo_description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hotelsimages',
            name='hotel_photo',
            field=models.ImageField(null=True, upload_to='hotels'),
        ),
    ]
