# Generated by Django 3.2.5 on 2021-07-29 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0002_amenity_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateamenity',
            name='amenity',
        ),
        migrations.AddField(
            model_name='rateamenity',
            name='amenity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hotelcontent.amenity', verbose_name='Amenity'),
        ),
        migrations.AlterField(
            model_name='rateamenity',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelcontent.rooms', verbose_name='Комната'),
        ),
    ]
