# Generated by Django 3.2.5 on 2021-07-28 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotelcontent', '0003_auto_20210728_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtypes',
            old_name='hotel_type_description',
            new_name='room_type_description',
        ),
        migrations.RenameField(
            model_name='roomtypes',
            old_name='hotel_type_name',
            new_name='room_type_name',
        ),
        migrations.RenameField(
            model_name='roomtypes',
            old_name='hotel_type_price',
            new_name='room_type_price',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='room_price',
        ),
        migrations.AddField(
            model_name='hotel',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='agent_reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelcontent.agentreservation'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booking_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelcontent.bookingstatus'),
        ),
    ]
