# Generated by Django 3.2.5 on 2021-07-28 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0004_auto_20210728_1315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coef',
            new_name='Coefficient',
        ),
        migrations.RenameField(
            model_name='coefficient',
            old_name='coef',
            new_name='Coefficient',
        ),
    ]
