# Generated by Django 3.2.5 on 2021-08-13 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0004_auto_20210813_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='hotel',
        ),
        migrations.AddField(
            model_name='bookings',
            name='hotels',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hotelcontent.hotel'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hotelcontent.rooms'),
        ),
    ]
