# Generated by Django 3.2.5 on 2021-08-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0002_auto_20210813_0058'),
        ('hotelcontent', '0004_auto_20210814_0312'),
    ]

    operations = [
    ]
