# Generated by Django 3.2.5 on 2021-07-30 18:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0005_rateamenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtypes',
            name='hotel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hotelcontent.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='coefficient',
            name='end_date',
            field=models.DateField(default=datetime.date(2021, 7, 30)),
        ),
        migrations.AlterField(
            model_name='coefficient',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 7, 30)),
        ),
    ]
