# Generated by Django 3.2.5 on 2021-07-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0006_auto_20210730_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_rate_price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=7),
        ),
    ]
