# Generated by Django 3.2.5 on 2021-08-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0006_auto_20210813_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='hotel_name_reserve',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='room_number_reserve',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hotelcontent.rooms'),
        ),
    ]
