# Generated by Django 3.2.5 on 2021-07-30 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0007_rooms_room_rate_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficient',
            name='end_date',
            field=models.DateField(default=datetime.date(2021, 7, 31)),
        ),
        migrations.AlterField(
            model_name='coefficient',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 7, 31)),
        ),
        migrations.RemoveField(
            model_name='rateamenity',
            name='amenity',
        ),
        migrations.AddField(
            model_name='rateamenity',
            name='amenity',
            field=models.ManyToManyField(to='hotelcontent.Amenity', verbose_name='Amenity'),
        ),
    ]
