# Generated by Django 3.2.5 on 2021-08-01 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0009_auto_20210731_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='vision',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coefficient',
            name='end_date',
            field=models.DateField(default=datetime.date(2021, 8, 1)),
        ),
        migrations.AlterField(
            model_name='coefficient',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 8, 1)),
        ),
    ]
