# Generated by Django 3.2.5 on 2021-08-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0009_alter_bookings_room_number_reserve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='room_number_reserve',
            new_name='room_number',
        ),
    ]
