# Generated by Django 3.2.5 on 2021-08-13 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0010_rename_room_number_reserve_bookings_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotelcontent.rooms'),
        ),
    ]
