# Generated by Django 3.2.5 on 2021-08-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0010_auto_20210801_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='vision',
            field=models.BooleanField(),
        ),
    ]
