# Generated by Django 3.2.5 on 2021-08-13 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0011_alter_bookings_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='hotel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='coefficient',
            name='end_date',
            field=models.DateField(default=datetime.date(2021, 8, 14)),
        ),
        migrations.AlterField(
            model_name='coefficient',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 8, 14)),
        ),
    ]
