# Generated by Django 3.2.5 on 2021-08-13 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0012_auto_20210814_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='hotels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotelcontent.hotel'),
        ),
    ]
