# Generated by Django 3.2.5 on 2021-08-14 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0013_alter_bookings_hotels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='room_price',
        ),
    ]
