# Generated by Django 3.2.5 on 2021-08-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0014_alter_amenity_vision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='vision',
        ),
    ]
