# Generated by Django 3.2.5 on 2021-08-03 14:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0015_remove_amenity_vision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficient',
            name='end_date',
            field=models.DateField(default=datetime.date(2021, 8, 3)),
        ),
        migrations.AlterField(
            model_name='coefficient',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 8, 3)),
        ),
        migrations.AlterField(
            model_name='rateamenity',
            name='amenity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='hotelcontent.amenity', verbose_name='Amenity'),
        ),
        migrations.AlterField(
            model_name='rateamenity',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotelcontent.rooms', verbose_name='Комната'),
        ),
    ]
