# Generated by Django 3.2.5 on 2021-08-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0016_remove_rooms_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=200.0, max_digits=7),
        ),
    ]
