# Generated by Django 3.2.5 on 2021-08-03 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelcontent', '0016_auto_20210803_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateamenity',
            name='amenity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hotelcontent.amenity', verbose_name='Amenity'),
        ),
        migrations.AlterField(
            model_name='rateamenity',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='hotelcontent.rooms', verbose_name='Комната'),
        ),
    ]
