name: Python application

on: [push]

jobs:
  run_tests:

    runs-on: ubuntu-latest
    env: 
      SECRET_KEY: 'secret-key'
      DB_PASS: "postgres"
      DB_USER: "postgres"
      DB_NAME: "github_actions"
      DEBUG: True
      DB_PORT: '5432'
      DB_HOST: 'localhost'
      ALLOWED_HOST: '127.0.0.1'
      API_KEY: 'some-api-key'
    
    services:
      db:
        image: postgres:12.3-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --mount type=tmpfs,destination=/var/lib/postgresql/data --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: python manage.py migrate
    - name: Run tests
      run: python manage.py test
