name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env: |
      SECRET_KEY: 'secret-key'
      DB_PASS: "db-pass"
      DB_USER: "db-user"
      DB_NAME: "db-name"
      DEBUG: True
      DB_PORT: '5432'
      DB_HOST: 'localhost'
      ALLOWED_HOST: '127.0.0.1'
      API_KEY: 'some-api-key'

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: python manage.py migrate
    - name: Run tests
      run: python manage.py test
